/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard/applications'
import { Route as DashboardInvitationsRouteImport } from './routes/dashboard/invitations'
import { Route as DashboardMembersRouteImport } from './routes/dashboard/members'
import { Route as DashboardPermissionsRouteImport } from './routes/dashboard/permissions'
import { Route as DashboardRolesRouteImport } from './routes/dashboard/roles'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvitationsRoute = DashboardInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPermissionsRoute = DashboardPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/applications'
    | '/dashboard/invitations'
    | '/dashboard/members'
    | '/dashboard/permissions'
    | '/dashboard/roles'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/applications'
    | '/dashboard/invitations'
    | '/dashboard/members'
    | '/dashboard/permissions'
    | '/dashboard/roles'
    | '/dashboard'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/applications'
    | '/dashboard/invitations'
    | '/dashboard/members'
    | '/dashboard/permissions'
    | '/dashboard/roles'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invitations': {
      id: '/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof DashboardInvitationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/permissions': {
      id: '/dashboard/permissions'
      path: '/permissions'
      fullPath: '/dashboard/permissions'
      preLoaderRoute: typeof DashboardPermissionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardInvitationsRoute: typeof DashboardInvitationsRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardPermissionsRoute: typeof DashboardPermissionsRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardInvitationsRoute: DashboardInvitationsRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardPermissionsRoute: DashboardPermissionsRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
